import Header from "@/components/Header";
import Head from "next/head";
import Footer from "@/components/Footer";
import "@/styles/globals.css";



export default function App({ Component, pageProps }) {
  return (
    <div style={{ minHeight: "100vh", position: "relative" }}>
      <Head>
        <title>Sandrine Herrault</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </div>
  );
}
